version: "3.9"

services:
  db:
    image: postgres:16
    container_name: twitter_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d twitter"]
      interval: 2s
      timeout: 3s
      retries: 15

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    # для локальной разработки удобно:
    command: /bin/sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
      - media_data:/code/app/media

volumes:
  postgres_data:
  media_data:
